import type { Rival } from '#/marketing/data/compare';

/** Comparisons against the hosted, closed-backend platforms. */
export const hostedRivals: Rival[] = [
  {
    slug: 'sanity',
    name: 'Sanity',
    tagline: 'Structured content with the schema in your repository.',
    summary:
      'Sanity is the strongest of the developer-first platforms. Content is genuinely structured, the query language is powerful, and the Studio is a real application you can extend. The trade is that the schema is a TypeScript file in a repository, so the content model belongs to whoever can open a pull request.',
    strength:
      'GROQ is the best query language in this category, the free tier is unusually generous at twenty seats, and Studio customisation goes further than any comparable UI.',
    theirs: {
      modelling:
        'Developers, in code. The schema is a file in the Studio repository, so a new field is a pull request and a deploy.',
      types:
        'Generated from your schema and your GROQ queries with the CLI, as a step you own and run.',
      change: 'Your own schema change, in your own repository, released on your own schedule.',
      analytics: 'Not included.',
      ai: 'AI Assist on paid plans.',
      hosting: 'Hosted only. The Studio is open source, the content backend is not self-hostable.',
      pricing: 'Free for 20 seats, then $15 per seat per month with usage-based overages.',
    },
    pickThem:
      'Pick Sanity if your content model is genuinely owned by engineering and you want it reviewed like code, or if you need querying more expressive than get-and-list.',
  },
  {
    slug: 'contentful',
    name: 'Contentful',
    tagline: 'The enterprise headless CMS, priced accordingly.',
    summary:
      'Contentful is the default choice for large organisations, and it earns that with governance, environments and a mature ecosystem. Modelling does happen in the UI, which is the right instinct. What is missing is the other half: nothing generates a typed client for you, and nothing protects your build when a field goes away.',
    strength:
      'Environments, roles and workflow governance are genuinely enterprise-grade, and the ecosystem of apps and integrations is the largest here.',
    theirs: {
      modelling: 'Marketing, in the web app. Content types are configured in the UI.',
      types: 'Generated by a separate CLI or community tools, wired up and kept current by you.',
      change: 'No deprecation path. Removing a field is a breaking change you coordinate by hand.',
      analytics: 'Not included.',
      ai: 'AI Actions, on Enterprise plans.',
      hosting: 'Hosted only. Not open source, not self-hostable.',
      pricing:
        'Free tier, then $300 per month for Lite, then Enterprise pricing on request. Locales and content types are capped per tier.',
    },
    pickThem:
      'Pick Contentful if you need multi-environment governance today, or if your organisation requires a vendor with that scale of compliance and support behind it.',
  },
  {
    slug: 'storyblok',
    name: 'Storyblok',
    tagline: 'A visual editor over your own rendered pages.',
    summary:
      'Storyblok is the most editor-friendly product in this list. Its visual editor renders your real front end in an iframe and lets marketers click the thing they want to change, which is a genuinely good experience. It also means Storyblok has an opinion about how your app is built, and the cost climbs with seats and traffic.',
    strength:
      'The visual editor is excellent, and for teams that assemble pages from components rather than write structured entries it is hard to beat.',
    theirs: {
      modelling: 'Marketing, in the UI, modelling components rather than plain fields.',
      types: 'Generated from the component schema by a CLI, as a step you own.',
      change: 'No deprecation path in the generated types.',
      analytics: 'Not included.',
      ai: 'AI credits, allocated per plan.',
      hosting: 'Hosted only. Not open source.',
      pricing:
        'Free for one seat, then $99 per month for five, then $15 per extra seat, with traffic and request caps per tier.',
    },
    pickThem:
      'Pick Storyblok if visual, in-page editing is the requirement your content team will judge the project on. Stet deliberately does not build that: rendering belongs to your app.',
  },
  {
    slug: 'prismic',
    name: 'Prismic',
    tagline: 'Page building from slices, priced per repository.',
    summary:
      'Prismic splits the difference: types can be defined in the UI or through Slice Machine in your repository, and marketers assemble pages from the slices developers build. Pricing is per repository rather than per person, which suits a single large site and suits a portfolio of small ones much less.',
    strength:
      'Slice Machine keeps the component library and the content model in step, and the per-repository pricing is very cheap for a small team on one site.',
    theirs: {
      modelling: 'Both. In the UI, or through Slice Machine in your repository.',
      types: 'Generated by Slice Machine for your slices and documents.',
      change: 'No deprecation path in the generated types.',
      analytics: 'Not included.',
      ai: 'An MCP server and CLI, so coding agents can model and populate content.',
      hosting: 'Hosted only. Not open source.',
      pricing:
        'Per repository, not per person: free for one user, $10 per month for three, rising to $675 for unlimited.',
    },
    pickThem:
      'Pick Prismic if you run one large marketing site with a big team, where per-repository pricing works out cheaper than paying per seat.',
  },
];
