// Generated by Stet from your content model. Do not edit: it is
// regenerated by @stetcms/vite or `stet generate`.
import { createContentClient } from '@stetcms/client';
import type { ContentEntryBase } from '@stetcms/client';

export type PostsEntry = ContentEntryBase & {
  fields: {
    "summary"?: string | null;
    "body"?: string | null;
    "author"?: { id: string; name: string } | null;
  };
};

export type LandingEntry = ContentEntryBase & {
  fields: {
    "headline"?: string | null;
    "pitch"?: string | null;
  };
};

export type ChangelogEntry = ContentEntryBase & {
  fields: {
  };
};

export type StetContentModel = {
  "posts": { kind: "collection"; entry: PostsEntry };
  "landing": { kind: "map"; entry: LandingEntry };
  "changelog": { kind: "collection"; entry: ChangelogEntry };
};

export const stet = createContentClient<StetContentModel>({
  origin: "http://localhost:3000",
  apiKey: typeof process === 'undefined' ? undefined : process.env.STET_API_KEY,
});
