// Generated by Stet from your content model. Do not edit: it is
// regenerated by @stetcms/vite or `stet generate`.
import { createContentClient } from '@stetcms/client';
import type { ContentEntryBase } from '@stetcms/client';

export type PostsEntry = ContentEntryBase & {
  fields: {
    "summary"?: string | null;
    "body"?: string | null;
  };
};

export type LandingEntry = ContentEntryBase & {
  fields: {
    "headline"?: string | null;
    "pitch"?: string | null;
  };
};

export type StetContentModel = {
  "posts": { kind: "collection"; entry: PostsEntry };
  "landing": { kind: "map"; entry: LandingEntry };
};

const origin =
  typeof process === 'undefined' ? "http://localhost:3000" : (process.env.STET_ORIGIN ?? "http://localhost:3000");

export const stet = createContentClient<StetContentModel>({
  origin,
  apiKey: typeof process === 'undefined' ? undefined : process.env.STET_API_KEY,
});
