import {
  ContractPrerequisite,
  defineConfig,
  LegalBases,
  Retention,
  Voluntary,
} from '@policystack/sdk';
import { brand } from '@repo/brand';

import * as scanned from './policystack.gen';

// The privacy policy and the cookie policy both derive from this one config
// (see @policystack/sdk). Scanned data categories, cookies, and third parties
// come from ./policystack.gen, generated by the policyStack() Vite plugin.
//
// There is no consent runtime and no banner. Nothing here is stored on a
// reader's device except what running the app requires, so there is nothing
// to ask permission for: product analytics are first-party and cookieless
// (see dogfooding/analytics). Reintroducing anything on a consent basis means
// bringing back a banner to gate it.
//
// Before launch: fill in the registered address (a placeholder, like
// MAIL_FROM and STRIPE_PRICE_PAID), review every purpose and retention
// below, and have a lawyer read the rendered output. PolicyStack is not
// legal advice.
export default defineConfig(
  {
    company: {
      name: brand.name,
      legalName: 'JXD Ltd',
      address: 'Replace with your registered company address',
      url: brand.url,
      contact: { email: brand.email },
      // Declares no DPO is appointed; appoint one and set details if your
      // processing requires it.
      dpo: { required: false },
    },
    effectiveDate: '2026-07-27',
    // UK company serving UK, EEA, and Californian users. All three are
    // hand-authored ('specific') policy texts in PolicyStack.
    jurisdictions: ['uk', 'eea', 'us-ca'],
    data: {
      collected: {
        'Account Information': ['Name', 'Email address', 'Profile image', 'Language preference'],
        'Organization Data': ['Organization name', 'Membership and roles', 'Invitations'],
        'Workspace Content': ['Notes', 'Uploaded images', 'Assistant conversations'],
        'Usage Data': ['Pages visited', 'Product events', 'Browser type'],
      },
      context: {
        'Account Information': {
          purpose: 'To authenticate you and operate your account',
          lawfulBasis: LegalBases.Contract,
          retention: Retention.UntilAccountDeletion,
          provision: ContractPrerequisite('We cannot create or operate your account.'),
        },
        'Organization Data': {
          purpose: 'To run shared workspaces, memberships, and billing per organization',
          lawfulBasis: LegalBases.Contract,
          retention: Retention.UntilAccountDeletion,
          provision: ContractPrerequisite('We cannot provide shared workspaces.'),
        },
        'Workspace Content': {
          purpose: 'To store and sync the content you and your organization create',
          lawfulBasis: LegalBases.Contract,
          retention: Retention.UntilAccountDeletion,
          provision: ContractPrerequisite('We cannot store or sync your content.'),
        },
        'Usage Data': {
          purpose: 'To understand product usage and improve the service',
          lawfulBasis: LegalBases.LegitimateInterests,
          retention: Retention.NinetyDays,
          provision: Voluntary('Product analytics only; the service works without it.'),
        },
      },
    },
    // Each enabled key becomes a consent category; 'consent' as the basis is
    // what gates it behind the banner. Only essential cookies are left: the
    // session and cookie-cache, plus the consent record itself. Analytics is
    // first-party and cookieless (see @dogfood/analytics), so it stores
    // nothing on the reader's device and has no category here.
    cookies: {
      used: { essential: true },
      context: {
        essential: { lawfulBasis: LegalBases.Contract },
      },
    },
    thirdParties: [
      {
        name: 'Cloudflare',
        purpose: 'Hosting, storage, and network security',
        policyUrl: 'https://www.cloudflare.com/privacypolicy/',
      },
      {
        name: 'Stripe',
        purpose: 'Subscription billing and payment processing',
        policyUrl: 'https://stripe.com/privacy',
      },
      {
        name: 'Resend',
        purpose: 'Transactional and notification email delivery',
        policyUrl: 'https://resend.com/legal/privacy-policy',
      },
      {
        name: 'Anthropic',
        purpose: 'AI assistant responses',
        policyUrl: 'https://www.anthropic.com/legal/privacy',
      },
    ],
    trackingTechnologies: [],
    automatedDecisionMaking: [],
  },
  scanned,
);
