/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SignRouteRouteImport } from './routes/sign/route'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingChangelogRouteImport } from './routes/_marketing/changelog'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingCookiesRouteImport } from './routes/_marketing/cookies'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing/privacy'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAdminRouteRouteImport } from './routes/app/admin/route'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppAuditRouteImport } from './routes/app/audit'
import { Route as AppImportRouteImport } from './routes/app/import'
import { Route as AppMediaRouteImport } from './routes/app/media'
import { Route as AppOrganizationRouteImport } from './routes/app/organization'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AssetsIdRouteImport } from './routes/assets/$id'
import { Route as InviteIdRouteImport } from './routes/invite/$id'
import { Route as MailUnsubscribeRouteImport } from './routes/mail/unsubscribe'
import { Route as OrgsNewRouteImport } from './routes/orgs/new'
import { Route as Sign2faRouteImport } from './routes/sign/2fa'
import { Route as SignForgotRouteImport } from './routes/sign/forgot'
import { Route as SignInRouteImport } from './routes/sign/in'
import { Route as SignLinkRouteImport } from './routes/sign/link'
import { Route as SignResetRouteImport } from './routes/sign/reset'
import { Route as SignUpRouteImport } from './routes/sign/up'
import { Route as MarketingBlogIndexRouteImport } from './routes/_marketing/blog.index'
import { Route as MarketingBlogSlugRouteImport } from './routes/_marketing/blog.$slug'
import { Route as MarketingCompareIndexRouteImport } from './routes/_marketing/compare.index'
import { Route as MarketingCompareRivalRouteImport } from './routes/_marketing/compare.$rival'
import { Route as MarketingFeaturesIndexRouteImport } from './routes/_marketing/features.index'
import { Route as MarketingFeaturesSlugRouteImport } from './routes/_marketing/features.$slug'
import { Route as MarketingForIndexRouteImport } from './routes/_marketing/for.index'
import { Route as MarketingForPersonaRouteImport } from './routes/_marketing/for.$persona'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFilesIdRouteImport } from './routes/api/files/$id'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppAdminOrganizationsRouteImport } from './routes/app/admin/organizations'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin/users'
import { Route as AppDevelopersKeysRouteImport } from './routes/app/developers.keys'
import { Route as AppDevelopersWebhooksRouteImport } from './routes/app/developers.webhooks'
import { Route as AppCCollectionIndexRouteImport } from './routes/app/c.$collection.index'
import { Route as AppMMapIndexRouteImport } from './routes/app/m.$map.index'
import { Route as AppMMapFieldRouteImport } from './routes/app/m.$map.$field'
import { Route as AppCCollectionEntryIndexRouteImport } from './routes/app/c.$collection.$entry.index'
import { Route as AppCCollectionEntryFieldRouteImport } from './routes/app/c.$collection.$entry.$field'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRouteRoute = SignRouteRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingChangelogRoute = MarketingChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCookiesRoute = MarketingCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AssetsIdRoute = AssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteIdRoute = InviteIdRouteImport.update({
  id: '/invite/$id',
  path: '/invite/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MailUnsubscribeRoute = MailUnsubscribeRouteImport.update({
  id: '/mail/unsubscribe',
  path: '/mail/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsNewRoute = OrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const Sign2faRoute = Sign2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => SignRouteRoute,
} as any)
const SignForgotRoute = SignForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => SignRouteRoute,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/in',
  path: '/in',
  getParentRoute: () => SignRouteRoute,
} as any)
const SignLinkRoute = SignLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => SignRouteRoute,
} as any)
const SignResetRoute = SignResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => SignRouteRoute,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/up',
  path: '/up',
  getParentRoute: () => SignRouteRoute,
} as any)
const MarketingBlogIndexRoute = MarketingBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBlogSlugRoute = MarketingBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCompareIndexRoute = MarketingCompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCompareRivalRoute = MarketingCompareRivalRouteImport.update({
  id: '/compare/$rival',
  path: '/compare/$rival',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesIndexRoute = MarketingFeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesSlugRoute = MarketingFeaturesSlugRouteImport.update({
  id: '/features/$slug',
  path: '/features/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingForIndexRoute = MarketingForIndexRouteImport.update({
  id: '/for/',
  path: '/for/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingForPersonaRoute = MarketingForPersonaRouteImport.update({
  id: '/for/$persona',
  path: '/for/$persona',
  getParentRoute: () => MarketingRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesIdRoute = ApiFilesIdRouteImport.update({
  id: '/api/files/$id',
  path: '/api/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminOrganizationsRoute = AppAdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppDevelopersKeysRoute = AppDevelopersKeysRouteImport.update({
  id: '/developers/keys',
  path: '/developers/keys',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDevelopersWebhooksRoute = AppDevelopersWebhooksRouteImport.update({
  id: '/developers/webhooks',
  path: '/developers/webhooks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCCollectionIndexRoute = AppCCollectionIndexRouteImport.update({
  id: '/c/$collection/',
  path: '/c/$collection/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMMapIndexRoute = AppMMapIndexRouteImport.update({
  id: '/m/$map/',
  path: '/m/$map/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMMapFieldRoute = AppMMapFieldRouteImport.update({
  id: '/m/$map/$field',
  path: '/m/$map/$field',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCCollectionEntryIndexRoute =
  AppCCollectionEntryIndexRouteImport.update({
    id: '/c/$collection/$entry/',
    path: '/c/$collection/$entry/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCCollectionEntryFieldRoute =
  AppCCollectionEntryFieldRouteImport.update({
    id: '/c/$collection/$entry/$field',
    path: '/c/$collection/$entry/$field',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/sign': typeof SignRouteRouteWithChildren
  '/': typeof MarketingIndexRoute
  '/device': typeof DeviceRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/changelog': typeof MarketingChangelogRoute
  '/contact': typeof MarketingContactRoute
  '/cookies': typeof MarketingCookiesRoute
  '/pricing': typeof MarketingPricingRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/import': typeof AppImportRoute
  '/app/media': typeof AppMediaRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/settings': typeof AppSettingsRoute
  '/assets/$id': typeof AssetsIdRoute
  '/invite/$id': typeof InviteIdRoute
  '/mail/unsubscribe': typeof MailUnsubscribeRoute
  '/orgs/new': typeof OrgsNewRoute
  '/sign/2fa': typeof Sign2faRoute
  '/sign/forgot': typeof SignForgotRoute
  '/sign/in': typeof SignInRoute
  '/sign/link': typeof SignLinkRoute
  '/sign/reset': typeof SignResetRoute
  '/sign/up': typeof SignUpRoute
  '/app/': typeof AppIndexRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/compare/$rival': typeof MarketingCompareRivalRoute
  '/features/$slug': typeof MarketingFeaturesSlugRoute
  '/for/$persona': typeof MarketingForPersonaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/app/admin/organizations': typeof AppAdminOrganizationsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/developers/keys': typeof AppDevelopersKeysRoute
  '/app/developers/webhooks': typeof AppDevelopersWebhooksRoute
  '/blog/': typeof MarketingBlogIndexRoute
  '/compare/': typeof MarketingCompareIndexRoute
  '/features/': typeof MarketingFeaturesIndexRoute
  '/for/': typeof MarketingForIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/m/$map/$field': typeof AppMMapFieldRoute
  '/app/c/$collection/': typeof AppCCollectionIndexRoute
  '/app/m/$map/': typeof AppMMapIndexRoute
  '/app/c/$collection/$entry/$field': typeof AppCCollectionEntryFieldRoute
  '/app/c/$collection/$entry/': typeof AppCCollectionEntryIndexRoute
}
export interface FileRoutesByTo {
  '/sign': typeof SignRouteRouteWithChildren
  '/device': typeof DeviceRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/changelog': typeof MarketingChangelogRoute
  '/contact': typeof MarketingContactRoute
  '/cookies': typeof MarketingCookiesRoute
  '/pricing': typeof MarketingPricingRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/import': typeof AppImportRoute
  '/app/media': typeof AppMediaRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/settings': typeof AppSettingsRoute
  '/assets/$id': typeof AssetsIdRoute
  '/invite/$id': typeof InviteIdRoute
  '/mail/unsubscribe': typeof MailUnsubscribeRoute
  '/orgs/new': typeof OrgsNewRoute
  '/sign/2fa': typeof Sign2faRoute
  '/sign/forgot': typeof SignForgotRoute
  '/sign/in': typeof SignInRoute
  '/sign/link': typeof SignLinkRoute
  '/sign/reset': typeof SignResetRoute
  '/sign/up': typeof SignUpRoute
  '/': typeof MarketingIndexRoute
  '/app': typeof AppIndexRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/compare/$rival': typeof MarketingCompareRivalRoute
  '/features/$slug': typeof MarketingFeaturesSlugRoute
  '/for/$persona': typeof MarketingForPersonaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/app/admin/organizations': typeof AppAdminOrganizationsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/developers/keys': typeof AppDevelopersKeysRoute
  '/app/developers/webhooks': typeof AppDevelopersWebhooksRoute
  '/blog': typeof MarketingBlogIndexRoute
  '/compare': typeof MarketingCompareIndexRoute
  '/features': typeof MarketingFeaturesIndexRoute
  '/for': typeof MarketingForIndexRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/m/$map/$field': typeof AppMMapFieldRoute
  '/app/c/$collection': typeof AppCCollectionIndexRoute
  '/app/m/$map': typeof AppMMapIndexRoute
  '/app/c/$collection/$entry/$field': typeof AppCCollectionEntryFieldRoute
  '/app/c/$collection/$entry': typeof AppCCollectionEntryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteRouteWithChildren
  '/sign': typeof SignRouteRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/device': typeof DeviceRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/_marketing/changelog': typeof MarketingChangelogRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/cookies': typeof MarketingCookiesRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/import': typeof AppImportRoute
  '/app/media': typeof AppMediaRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/settings': typeof AppSettingsRoute
  '/assets/$id': typeof AssetsIdRoute
  '/invite/$id': typeof InviteIdRoute
  '/mail/unsubscribe': typeof MailUnsubscribeRoute
  '/orgs/new': typeof OrgsNewRoute
  '/sign/2fa': typeof Sign2faRoute
  '/sign/forgot': typeof SignForgotRoute
  '/sign/in': typeof SignInRoute
  '/sign/link': typeof SignLinkRoute
  '/sign/reset': typeof SignResetRoute
  '/sign/up': typeof SignUpRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/app/': typeof AppIndexRoute
  '/_marketing/blog/$slug': typeof MarketingBlogSlugRoute
  '/_marketing/compare/$rival': typeof MarketingCompareRivalRoute
  '/_marketing/features/$slug': typeof MarketingFeaturesSlugRoute
  '/_marketing/for/$persona': typeof MarketingForPersonaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/app/admin/organizations': typeof AppAdminOrganizationsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/developers/keys': typeof AppDevelopersKeysRoute
  '/app/developers/webhooks': typeof AppDevelopersWebhooksRoute
  '/_marketing/blog/': typeof MarketingBlogIndexRoute
  '/_marketing/compare/': typeof MarketingCompareIndexRoute
  '/_marketing/features/': typeof MarketingFeaturesIndexRoute
  '/_marketing/for/': typeof MarketingForIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/m/$map/$field': typeof AppMMapFieldRoute
  '/app/c/$collection/': typeof AppCCollectionIndexRoute
  '/app/m/$map/': typeof AppMMapIndexRoute
  '/app/c/$collection/$entry/$field': typeof AppCCollectionEntryFieldRoute
  '/app/c/$collection/$entry/': typeof AppCCollectionEntryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/sign'
    | '/'
    | '/device'
    | '/llms.txt'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/app/admin'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/pricing'
    | '/privacy'
    | '/app/analytics'
    | '/app/audit'
    | '/app/import'
    | '/app/media'
    | '/app/organization'
    | '/app/settings'
    | '/assets/$id'
    | '/invite/$id'
    | '/mail/unsubscribe'
    | '/orgs/new'
    | '/sign/2fa'
    | '/sign/forgot'
    | '/sign/in'
    | '/sign/link'
    | '/sign/reset'
    | '/sign/up'
    | '/app/'
    | '/blog/$slug'
    | '/compare/$rival'
    | '/features/$slug'
    | '/for/$persona'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/api/v1/$'
    | '/app/admin/organizations'
    | '/app/admin/users'
    | '/app/developers/keys'
    | '/app/developers/webhooks'
    | '/blog/'
    | '/compare/'
    | '/features/'
    | '/for/'
    | '/app/admin/'
    | '/app/m/$map/$field'
    | '/app/c/$collection/'
    | '/app/m/$map/'
    | '/app/c/$collection/$entry/$field'
    | '/app/c/$collection/$entry/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign'
    | '/device'
    | '/llms.txt'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/pricing'
    | '/privacy'
    | '/app/analytics'
    | '/app/audit'
    | '/app/import'
    | '/app/media'
    | '/app/organization'
    | '/app/settings'
    | '/assets/$id'
    | '/invite/$id'
    | '/mail/unsubscribe'
    | '/orgs/new'
    | '/sign/2fa'
    | '/sign/forgot'
    | '/sign/in'
    | '/sign/link'
    | '/sign/reset'
    | '/sign/up'
    | '/'
    | '/app'
    | '/blog/$slug'
    | '/compare/$rival'
    | '/features/$slug'
    | '/for/$persona'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/api/v1/$'
    | '/app/admin/organizations'
    | '/app/admin/users'
    | '/app/developers/keys'
    | '/app/developers/webhooks'
    | '/blog'
    | '/compare'
    | '/features'
    | '/for'
    | '/app/admin'
    | '/app/m/$map/$field'
    | '/app/c/$collection'
    | '/app/m/$map'
    | '/app/c/$collection/$entry/$field'
    | '/app/c/$collection/$entry'
  id:
    | '__root__'
    | '/app'
    | '/sign'
    | '/_marketing'
    | '/device'
    | '/llms.txt'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/app/admin'
    | '/_marketing/changelog'
    | '/_marketing/contact'
    | '/_marketing/cookies'
    | '/_marketing/pricing'
    | '/_marketing/privacy'
    | '/app/analytics'
    | '/app/audit'
    | '/app/import'
    | '/app/media'
    | '/app/organization'
    | '/app/settings'
    | '/assets/$id'
    | '/invite/$id'
    | '/mail/unsubscribe'
    | '/orgs/new'
    | '/sign/2fa'
    | '/sign/forgot'
    | '/sign/in'
    | '/sign/link'
    | '/sign/reset'
    | '/sign/up'
    | '/_marketing/'
    | '/app/'
    | '/_marketing/blog/$slug'
    | '/_marketing/compare/$rival'
    | '/_marketing/features/$slug'
    | '/_marketing/for/$persona'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/api/v1/$'
    | '/app/admin/organizations'
    | '/app/admin/users'
    | '/app/developers/keys'
    | '/app/developers/webhooks'
    | '/_marketing/blog/'
    | '/_marketing/compare/'
    | '/_marketing/features/'
    | '/_marketing/for/'
    | '/app/admin/'
    | '/app/m/$map/$field'
    | '/app/c/$collection/'
    | '/app/m/$map/'
    | '/app/c/$collection/$entry/$field'
    | '/app/c/$collection/$entry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SignRouteRoute: typeof SignRouteRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  DeviceRoute: typeof DeviceRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AssetsIdRoute: typeof AssetsIdRoute
  InviteIdRoute: typeof InviteIdRoute
  MailUnsubscribeRoute: typeof MailUnsubscribeRoute
  OrgsNewRoute: typeof OrgsNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesIdRoute: typeof ApiFilesIdRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/changelog': {
      id: '/_marketing/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof MarketingChangelogRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/cookies': {
      id: '/_marketing/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof MarketingCookiesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/media': {
      id: '/app/media'
      path: '/media'
      fullPath: '/app/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/organization': {
      id: '/app/organization'
      path: '/organization'
      fullPath: '/app/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/assets/$id': {
      id: '/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AssetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$id': {
      id: '/invite/$id'
      path: '/invite/$id'
      fullPath: '/invite/$id'
      preLoaderRoute: typeof InviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/unsubscribe': {
      id: '/mail/unsubscribe'
      path: '/mail/unsubscribe'
      fullPath: '/mail/unsubscribe'
      preLoaderRoute: typeof MailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/new': {
      id: '/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof OrgsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/2fa': {
      id: '/sign/2fa'
      path: '/2fa'
      fullPath: '/sign/2fa'
      preLoaderRoute: typeof Sign2faRouteImport
      parentRoute: typeof SignRouteRoute
    }
    '/sign/forgot': {
      id: '/sign/forgot'
      path: '/forgot'
      fullPath: '/sign/forgot'
      preLoaderRoute: typeof SignForgotRouteImport
      parentRoute: typeof SignRouteRoute
    }
    '/sign/in': {
      id: '/sign/in'
      path: '/in'
      fullPath: '/sign/in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof SignRouteRoute
    }
    '/sign/link': {
      id: '/sign/link'
      path: '/link'
      fullPath: '/sign/link'
      preLoaderRoute: typeof SignLinkRouteImport
      parentRoute: typeof SignRouteRoute
    }
    '/sign/reset': {
      id: '/sign/reset'
      path: '/reset'
      fullPath: '/sign/reset'
      preLoaderRoute: typeof SignResetRouteImport
      parentRoute: typeof SignRouteRoute
    }
    '/sign/up': {
      id: '/sign/up'
      path: '/up'
      fullPath: '/sign/up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof SignRouteRoute
    }
    '/_marketing/blog/': {
      id: '/_marketing/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof MarketingBlogIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/blog/$slug': {
      id: '/_marketing/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof MarketingBlogSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/compare/': {
      id: '/_marketing/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof MarketingCompareIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/compare/$rival': {
      id: '/_marketing/compare/$rival'
      path: '/compare/$rival'
      fullPath: '/compare/$rival'
      preLoaderRoute: typeof MarketingCompareRivalRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/': {
      id: '/_marketing/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof MarketingFeaturesIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/$slug': {
      id: '/_marketing/features/$slug'
      path: '/features/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof MarketingFeaturesSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/for/': {
      id: '/_marketing/for/'
      path: '/for'
      fullPath: '/for/'
      preLoaderRoute: typeof MarketingForIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/for/$persona': {
      id: '/_marketing/for/$persona'
      path: '/for/$persona'
      fullPath: '/for/$persona'
      preLoaderRoute: typeof MarketingForPersonaRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$id': {
      id: '/api/files/$id'
      path: '/api/files/$id'
      fullPath: '/api/files/$id'
      preLoaderRoute: typeof ApiFilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/organizations': {
      id: '/app/admin/organizations'
      path: '/organizations'
      fullPath: '/app/admin/organizations'
      preLoaderRoute: typeof AppAdminOrganizationsRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/developers/keys': {
      id: '/app/developers/keys'
      path: '/developers/keys'
      fullPath: '/app/developers/keys'
      preLoaderRoute: typeof AppDevelopersKeysRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/developers/webhooks': {
      id: '/app/developers/webhooks'
      path: '/developers/webhooks'
      fullPath: '/app/developers/webhooks'
      preLoaderRoute: typeof AppDevelopersWebhooksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/c/$collection/': {
      id: '/app/c/$collection/'
      path: '/c/$collection'
      fullPath: '/app/c/$collection/'
      preLoaderRoute: typeof AppCCollectionIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/m/$map/': {
      id: '/app/m/$map/'
      path: '/m/$map'
      fullPath: '/app/m/$map/'
      preLoaderRoute: typeof AppMMapIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/m/$map/$field': {
      id: '/app/m/$map/$field'
      path: '/m/$map/$field'
      fullPath: '/app/m/$map/$field'
      preLoaderRoute: typeof AppMMapFieldRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/c/$collection/$entry/': {
      id: '/app/c/$collection/$entry/'
      path: '/c/$collection/$entry'
      fullPath: '/app/c/$collection/$entry/'
      preLoaderRoute: typeof AppCCollectionEntryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/c/$collection/$entry/$field': {
      id: '/app/c/$collection/$entry/$field'
      path: '/c/$collection/$entry/$field'
      fullPath: '/app/c/$collection/$entry/$field'
      preLoaderRoute: typeof AppCCollectionEntryFieldRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminOrganizationsRoute: typeof AppAdminOrganizationsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminOrganizationsRoute: AppAdminOrganizationsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppImportRoute: typeof AppImportRoute
  AppMediaRoute: typeof AppMediaRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDevelopersKeysRoute: typeof AppDevelopersKeysRoute
  AppDevelopersWebhooksRoute: typeof AppDevelopersWebhooksRoute
  AppMMapFieldRoute: typeof AppMMapFieldRoute
  AppCCollectionIndexRoute: typeof AppCCollectionIndexRoute
  AppMMapIndexRoute: typeof AppMMapIndexRoute
  AppCCollectionEntryFieldRoute: typeof AppCCollectionEntryFieldRoute
  AppCCollectionEntryIndexRoute: typeof AppCCollectionEntryIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditRoute: AppAuditRoute,
  AppImportRoute: AppImportRoute,
  AppMediaRoute: AppMediaRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppDevelopersKeysRoute: AppDevelopersKeysRoute,
  AppDevelopersWebhooksRoute: AppDevelopersWebhooksRoute,
  AppMMapFieldRoute: AppMMapFieldRoute,
  AppCCollectionIndexRoute: AppCCollectionIndexRoute,
  AppMMapIndexRoute: AppMMapIndexRoute,
  AppCCollectionEntryFieldRoute: AppCCollectionEntryFieldRoute,
  AppCCollectionEntryIndexRoute: AppCCollectionEntryIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface SignRouteRouteChildren {
  Sign2faRoute: typeof Sign2faRoute
  SignForgotRoute: typeof SignForgotRoute
  SignInRoute: typeof SignInRoute
  SignLinkRoute: typeof SignLinkRoute
  SignResetRoute: typeof SignResetRoute
  SignUpRoute: typeof SignUpRoute
}

const SignRouteRouteChildren: SignRouteRouteChildren = {
  Sign2faRoute: Sign2faRoute,
  SignForgotRoute: SignForgotRoute,
  SignInRoute: SignInRoute,
  SignLinkRoute: SignLinkRoute,
  SignResetRoute: SignResetRoute,
  SignUpRoute: SignUpRoute,
}

const SignRouteRouteWithChildren = SignRouteRoute._addFileChildren(
  SignRouteRouteChildren,
)

interface MarketingRouteChildren {
  MarketingChangelogRoute: typeof MarketingChangelogRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingCookiesRoute: typeof MarketingCookiesRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingBlogSlugRoute: typeof MarketingBlogSlugRoute
  MarketingCompareRivalRoute: typeof MarketingCompareRivalRoute
  MarketingFeaturesSlugRoute: typeof MarketingFeaturesSlugRoute
  MarketingForPersonaRoute: typeof MarketingForPersonaRoute
  MarketingBlogIndexRoute: typeof MarketingBlogIndexRoute
  MarketingCompareIndexRoute: typeof MarketingCompareIndexRoute
  MarketingFeaturesIndexRoute: typeof MarketingFeaturesIndexRoute
  MarketingForIndexRoute: typeof MarketingForIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingChangelogRoute: MarketingChangelogRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingCookiesRoute: MarketingCookiesRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingBlogSlugRoute: MarketingBlogSlugRoute,
  MarketingCompareRivalRoute: MarketingCompareRivalRoute,
  MarketingFeaturesSlugRoute: MarketingFeaturesSlugRoute,
  MarketingForPersonaRoute: MarketingForPersonaRoute,
  MarketingBlogIndexRoute: MarketingBlogIndexRoute,
  MarketingCompareIndexRoute: MarketingCompareIndexRoute,
  MarketingFeaturesIndexRoute: MarketingFeaturesIndexRoute,
  MarketingForIndexRoute: MarketingForIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  SignRouteRoute: SignRouteRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  DeviceRoute: DeviceRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AssetsIdRoute: AssetsIdRoute,
  InviteIdRoute: InviteIdRoute,
  MailUnsubscribeRoute: MailUnsubscribeRoute,
  OrgsNewRoute: OrgsNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesIdRoute: ApiFilesIdRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
