// Generated by Stet from your content model. Do not edit: it is
// regenerated by @stetcms/vite or `stet generate`.
import { createContentClient } from '@stetcms/client';
import type { ContentEntryBase } from '@stetcms/client';

export type PostsEntry = ContentEntryBase & {
  fields: {
    "author"?: { id: string; name: string } | null;
    "published"?: string | null;
    "summary"?: string | null;
    "tags"?: ("Company" | "Engineering")[] | null;
    "body"?: string | null;
  };
};

export type StetContentModel = {
  "posts": { kind: "collection"; entry: PostsEntry };
};

const origin =
  typeof process === 'undefined' ? "https://stetcms.com" : (process.env.STET_ORIGIN ?? "https://stetcms.com");

export const stet = createContentClient<StetContentModel>({
  origin,
  apiKey: typeof process === 'undefined' ? undefined : process.env.STET_API_KEY,
});
