/**
 * The codegen behind `@stetcms/vite` and the CLI's `stet generate`: fetch an
 * organization's content model and render the typed `stet.gen.ts` module.
 *
 * Import-free on purpose: build tools load this entry under plain Node, where
 * the rest of the package's import chain is not resolvable from source.
 */

/**
 * The hosted Stet deployment. Pass `origin` to target a local dev server or
 * a self-hosted instance instead.
 */
export const DEFAULT_ORIGIN = 'https://stetcms.com';

/** The `/api/v1/model` payload the module is generated from. */
export type ContentModel = {
  types: {
    slug: string;
    name: string;
    kind: 'collection' | 'map';
    fields: { key: string; name: string; type: string; options: { name: string }[] }[];
  }[];
};

/** Fetches the content model the given API key's organization has shaped. */
export async function fetchContentModel(origin: string, apiKey: string): Promise<ContentModel> {
  const response = await fetch(`${origin}/api/v1/model`, { headers: { 'x-api-key': apiKey } });
  if (!response.ok) {
    throw new Error(`GET ${origin}/api/v1/model responded ${response.status}`);
  }
  return (await response.json()) as ContentModel;
}

/** `case-studies` → `CaseStudiesEntry`; never starts with a digit. */
export function entryTypeName(slug: string): string {
  const pascal = slug
    .split(/[^a-zA-Z0-9]+/)
    .filter((part) => part.length > 0)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
  return /^[A-Za-z]/.test(pascal) ? `${pascal}Entry` : `Stet${pascal}Entry`;
}

function optionUnion(options: { name: string }[]): string {
  if (options.length === 0) {
    return 'string';
  }
  return options.map((option) => JSON.stringify(option.name)).join(' | ');
}

function fieldTsType(field: ContentModel['types'][number]['fields'][number]): string {
  switch (field.type) {
    case 'number':
      return 'number';
    case 'checkbox':
      return 'boolean';
    case 'person':
      return '{ id: string; name: string }';
    case 'select':
      return optionUnion(field.options);
    case 'multi_select':
      return field.options.length === 0 ? 'string[]' : `(${optionUnion(field.options)})[]`;
    // text, rich_text (markdown), date, and link all travel as strings.
    default:
      return 'string';
  }
}

/**
 * Renders the generated `stet.gen.ts`: one entry type per collection or map
 * and a `stet` client typed by them. The API key is read from the
 * environment at runtime, never embedded, so the file is safe to commit.
 */
export function renderContentModule(model: ContentModel, origin: string): string {
  const lines: string[] = [
    '// Generated by Stet from your content model. Do not edit: it is',
    '// regenerated by @stetcms/vite or `stet generate`.',
    "import { createContentClient } from '@stetcms/client';",
    "import type { ContentEntryBase } from '@stetcms/client';",
    '',
  ];

  for (const type of model.types) {
    lines.push(`export type ${entryTypeName(type.slug)} = ContentEntryBase & {`, '  fields: {');
    for (const field of type.fields) {
      lines.push(`    ${JSON.stringify(field.key)}?: ${fieldTsType(field)} | null;`);
    }
    lines.push('  };', '};', '');
  }

  lines.push('export type StetContentModel = {');
  for (const type of model.types) {
    lines.push(
      `  ${JSON.stringify(type.slug)}: { kind: ${JSON.stringify(type.kind)}; entry: ${entryTypeName(type.slug)} };`,
    );
  }
  lines.push('};', '');

  lines.push(
    'export const stet = createContentClient<StetContentModel>({',
    `  origin: ${JSON.stringify(origin)},`,
    "  apiKey: typeof process === 'undefined' ? undefined : process.env.STET_API_KEY,",
    '});',
    '',
  );

  return lines.join('\n');
}
